apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      serviceAccountName: agent-sa
      containers:
      - name: agent
        image: hardik0811arora/ai-agent:latest
        ports:
        - containerPort: 8000
